name: medicare
description: "Your Health Partner - An app to connect health experts with patients for seamless healthcare solutions."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Application versioning
version: 1.0.0+1

# Environment constraints
environment:
  sdk: ">=3.5.1 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.5
  cupertino_icons: ^1.0.8
  async: any
  collection: any

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  assets:
    - assets/images/doctor.png
    - assets/images/verify_email-removebg-preview.png
    - assets/images/profilepicture.png
