name: medicare
description: "Your Health Partner - An app to connect health experts with patients for seamless healthcare solutions."

# Prevent accidental publication to pub.dev
publish_to: 'none'

# Application versioning
version: 1.0.0+1

# Environment constraints
environment:
  sdk: ">=3.5.1 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.1.5
  cupertino_icons: ^1.0.8
  google_sign_in: ^5.4.2
  async: ^2.11.0
  collection: ^1.18.0

# Development dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Asset declarations
  assets:
    - assets/images/doctor.png
    - assets/images/verify_email-removebg-preview.png
    - assets/images/profilepicture.png
    - assets/images/avatar1.jpg
    - assets/images/doctor.jpg
    - assets/images/team2.png
    - assets/images/pharmacy1.jpg
    - assets/images/pharmacy2.jpg
    - assets/images/hospital1.jpg
    - assets/images/hospital2.jpg